### ISSUE TITLE
Change string representation of the yasa.Hypnogram class (__repr__)

### ISSUE THREAD

**Issue by raphaelvallat** [raphaelvallat/yasa#128]
@remrama I was thinking that to avoid any confusion, we could change the string representation of the `yasa.Hypnogram` class to *not* print the pandas.Series but instead some general statistics, _a la_ [mne.Raw](https://github.com/mne-tools/mne-python/blob/e5086fcb20e891ef1c4ddc2ce2ae16047b496c5f/mne/io/base.py#L1733)

```python
def __repr__(self):
    # return f"{self.hypno}"
    return (
        f"<yasa.Hypnogram | A {self.duration} minutes hypnogram, with {self.n_stages} stages and {self.freq} resolution>\n"
        " - Use `.hypno` to get the values as a pandas.Series"
    )
```

which gives:

![image](https://user-images.githubusercontent.com/25703792/210118804-fcb98bae-b42a-4f68-ba9f-5f35fc10d8dc.png)

I still think that I prefer the original output as a shortcut to the pandas.Series, but would be ready to change if you feel strongly about this new approach.

**Comment by remrama** [comment]
YES enthusiastic support. This confused me about the Hypnogram class at first, but got used to it. I still was tempted sometimes to try and apply Pandas methods to the Hypnogram object :/

This avoids confusion but also has the benefit of providing more information in the string (you're example here is already useful and would be enough tbh).

**Comment by remrama** [comment]
> I still think that I prefer the original output as a shortcut to the pandas.Series

Oh I see what you mean now -- that you would still have the pandas.Series view when interacting with yasa.Hypnogram interactively. Hmm, I could see it either way, but I think for clarity it makes sense to have this string representation there as well. No strong opinion though! Whatever you think is good.

**Comment by raphaelvallat** [comment]
> YES enthusiastic support.

I'll make the change then :) I think it will be confusing to users otherwise.
