### ISSUE TITLE
YASA 0.6.3 issue

### ISSUE THREAD

**Issue by sjg2203** [raphaelvallat/yasa#131]
Brilliant job you have done, tremendous contribution to the field!
Though, I just noticed that with version `0.6.3`, I had to downgrade `Matplotlib` from `3.6.2` to `3.6.0` on my intel Windows and both my intel and ARM macs and that I couldn't update some packages such as `Charset-normaliser` `2.1.1` (now `3.0.1`) and `NumPy` `1.23.5` (now `1.24.1`) otherwise `YASA` would not generate a plot nor work as intended

**Comment by raphaelvallat** [comment]
Thanks @sjg2203 ! Can you please provide more details? What error did you get when trying to plot? Which YASA function(s) were you using? Did you get a warning when upgrading yasa with pip?

It's the first time that I hear about `charset-normaliser` so I'm not sure how this can be related to YASA though.

**Comment by matiasandina** [comment]
Also encountering this problem after numpy update

```
np.__version__
'1.24.2'
```
Issue happens directly on yasa import.

**Comment by umair-hassan** [comment]
Creating a virtual environment (venv) helped resolve the issue for me. A virtual environment provides a self-contained Python environment with its own installed packages, separate from the system-wide Python installation. This allowed me to have different versions of packages and avoid conflicts between dependencies.

I also downloaded by enforcing to get out of python cache using this:
`pip install --no-cache-dir -r requirements.txt
`

the venv was just simply created in root directory using

`python3 -m venv mycurrentdirectory
`

@raphaelvallat  If you'd like, I can push a detailed introduction doc along with a helpful example to guide the user in setting up such venv YASA. Let me know, thanks!
