### ISSUE TITLE
IRASA- periodic power values 

### ISSUE THREAD

**Issue by apoorva6262** [raphaelvallat/yasa#136]
Hi @raphaelvallat ,

I used the following function to determine the periodic power from the signal : 
`freqs, psd_aperiodic, psd_osc, fit_params = yasa.irasa(sig, Fs, band=[3,60],kwargs_welch={'average': 'median'})`

This gave me the output for average periodic power (`np.nanmean(psd_osc)`) as 4.913666773031852e-14.

I tried neurodsp package (https://neurodsp-tools.github.io/neurodsp/auto_tutorials/aperiodic/plot_IRASA.html?highlight=irasa) with same settings and I got the average periodic power to be 1.3315638777465248e-13. Wondering what could cause the difference? I used the same welch and median method to determine the psd. 

Additionally how do you determine the periodic power for a subset of band frequencies like alpha from the initial fit ? Right now I have set the band parameter to 3-60hz, but how do I extract alpha frequencies from the fit itself ? I did not want to set the initial band paramaters to 8,12hz as that is a small range to find the aperiodic fit. I tried indexing but that gave me some shape issue. 

Thanks,
Apoorva.

**Comment by raphaelvallat** [comment]
Hi @apoorva6262,

Regarding your first question, these two values are actually both zero: 

```python
np.isclose(4.913666773031852e-14, 1.3315638777465248e-13)  # True
np.isclose(4.913666773031852e-14, 0)  # Also true
```

For your second question, I would recommend using the yasa.bandpower_from_psd function (https://raphaelvallat.com/yasa/build/html/generated/yasa.bandpower_from_psd.html):

```python
yasa.bandpower_from_psd(psd_osc, freqs, band=[(8, 12, "Alpha")])
```

Hope this helps,
Raphael

**Comment by apoorva6262** [comment]
@raphaelvallat ,
For the second question, I replaced psd for 'psd_osc' in 'yasa.bandpower_from_psd' as I am interested in periodic peaks only : 
```
freqs, psd_aperiodic, psd_osc, fit_params = yasa.irasa(sig, Fs, band=[3,60],kwargs_welch={'average': 'median'})
yasa.bandpower_from_psd(psd_osc, freqs, ch_names=['F7'], bands=[ 4, 8, 'Theta', 8, 12, 'Alpha',  13, 30, 
                                                         'Beta'], relative=True) 
```
The shape of psd_osc is (1,229) , freqs is (229), both are numpy arrays. 
But I get this error:
TypeError: 'int' object is not subscriptable

    
    
<img width="1010" alt="Screen Shot 2023-02-13 at 11 18 35 AM" src="https://user-images.githubusercontent.com/76274425/218553136-84c7f10c-6f14-4ddd-8a4c-6124fba42761.png">

**Comment by raphaelvallat** [comment]
Please try the following:

```python
yasa.bandpower_from_psd(psd_osc, freqs, ch_names=['F7'], bands=[(4, 8, 'Theta'), (8, 12, 'Alpha'), (13, 30,  'Beta')], relative=True) 
```

**Comment by raphaelvallat** [comment]
Unfortunately I do not have new solutions to this problem :/ Have you tried using [FOOOF](https://fooof-tools.github.io/fooof/)? It is also a great alternative to IRASA.

**Comment by apoorva6262** [comment]
No worries, I did try FOOOF and that is great. I am actually comparing IRASA to FOOOF

**Comment by apoorva6262** [comment]
Another question, I am running this IRASA function to determine periodic power. For some files, I see that the fit(r2 value)  is poor. Do you have any suggestions as to how to exclude poor fits or any outlier methods you employ for further statistical analysis?

**Comment by raphaelvallat** [comment]
I have not used IRASA in a long time for my own analyses so it's hard to say. I would probably not exclude a night just based on a poor R^2 value. But I do recommend plotting the full, aperiodic, and periodic spectra to get a better idea of what may be happening.

**Comment by apoorva6262** [comment]
Thanks! With my dataset, I am determining power across all 32 eeg channels for three different groups. For consistency sake, I have made sure to use the same settings of IRASA for all the channels and for all subjects in different groups. But there are  1-2 subjects with poor fits due to noise in higher frequencies (r2=0.002) , would you recommend just reporting the noise? It wouldn't make sense to use different settings for each file/subject to get a better fit.

**Comment by raphaelvallat** [comment]
Can you try to filter out the high-freq noise for these 1-2 participants? If the power spectrum is really too noisy then I don't think it's worth calculating IRASA honestly, the results will likely be biased.

**Comment by apoorva6262** [comment]
<img width="456" alt="Screen Shot 2023-02-22 at 7 09 22 PM" src="https://user-images.githubusercontent.com/76274425/220813278-da08fead-f2ad-414e-8cef-ca15da8bf8a9.png">


The original spectrum is weird, it does not have a typical 1/f pattern

**Comment by apoorva6262** [comment]
<img width="612" alt="Screen Shot 2023-03-01 at 10 37 53 AM" src="https://user-images.githubusercontent.com/76274425/222234081-5b5e88a9-7c16-4998-8fc3-0c032c011c9d.png">


Also , I have this issue of negative psd issue with vast majority of subjects, i have used the default resampling method.
