### ISSUE TITLE
sw_detection, How to improve its accuracy?

### ISSUE THREAD

**Issue by songhat** [raphaelvallat/yasa#137]
When I use it, there will always be misidentification and missing some instance . How to improve it? 
![image](https://user-images.githubusercontent.com/48643755/221466031-b1296c75-96d3-4627-a456-645331e3b3f0.png)
![image](https://user-images.githubusercontent.com/48643755/221466109-13aecdb5-7619-402a-b015-38e9471fa8f2.png)

**Comment by raphaelvallat** [comment]
Hi @1358467720,

Are you using the default parameters? Have you tried changing the parameters of `yasa.sw_detect`? Did you apply any preprocessing to your data before running the SW detection?

As explained in the [FAQ](https://raphaelvallat.com/yasa/build/html/faq.html#best_params), I recommend manually annotating slow-waves or spindles events on a few representative recording of your own dataset, and then finding the parameters that give you the best agreement with your manual detection. This is the only way to get results that reflect your "own" scoring, especially for spindles detection.

Hope this helps,
Raphael
