### ISSUE TITLE
extract fractal noise

### ISSUE THREAD

**Issue by MZeydabadi** [raphaelvallat/yasa#142]
Is this implemented in YASA:

another method to extract fractal noise, please refer to

https://github.com/fooof-tools/fooof
https://www.biorxiv.org/content/10.1101/299859v1

**Comment by raphaelvallat** [comment]
Hi @MZeydabadi,

FOOOF is not implemented in YASA. I don't think there's a need for it since the FOOOF library is great and easy-to-use.

**Comment by MZeydabadi** [comment]
Understood. What is not clear to me in using either IRISA or FOOOF, how can one remove the 1/f noise from the signal in the time domain. I appreciate if you could elaborate on this.

**Comment by raphaelvallat** [comment]
Hmm, I'm not sure about FOOOF so I would recommend opening an issue in their GitHUb. As for IRASA, I don't think that it is possible to reconstruct the signal in the time-domain. You can only analyse it in the frequency domain.
