### ISSUE TITLE
Question about Power Spectral Analysis

### ISSUE THREAD

**Issue by PhD-GOAT** [raphaelvallat/yasa#147]
I want to use the bandpower function of Spectral analysis.

How do I split the rawEDF instance loaded from the mne to see band power every 30 second epoch?

code like

`raw[0:3000]`

When used for band power like that, an error message "AssertionError: Data must be a numpy array." appears.

**Comment by raphaelvallat** [comment]
Hi @PhD-GOAT,

I would try the following (not tested):

```python
data = raw.get_data(picks="C4-M1", units="uV")  # Pick a single channel, here C4-M1
data = np.squeeze(data) 
sf = raw.info["sfreq"]
times, epochs = yasa.sliding_window(data, sf, window=30)
bp = yasa.bandpower(epochs, sf, win_sec=5)
```

Alternatively you can use the `yasa.SleepStaging.get_features()` [method](https://raphaelvallat.com/yasa/build/html/generated/yasa.SleepStaging.html#yasa.SleepStaging):

Thanks
Raphael

**Comment by PhD-GOAT** [comment]
aha, yasa.SleepStaging.get_features() Does this function output the data you have applied to machine learning as a result value?

**Comment by raphaelvallat** [comment]
Correct @PhD-GOAT , this function outputs the features (30-sec resolution) that are then sent to the machine-learning model for sleep stage classification.
