### ISSUE TITLE
Typo: REM latency

### ISSUE THREAD

**Issue by laura-hainke** [raphaelvallat/yasa#173]
In the documentation page for the sleep_statistics() function (https://raphaelvallat.com/yasa/build/html/generated/yasa.sleep_statistics.html#yasa.sleep_statistics), the following warning is described: 

"Warning

The definition of REM latency in the AASM scoring manual differs from the REM latency reported here. The former uses the time from first epoch of sleep, while YASA uses the time from the beginning of the recording. The AASM definition of the REM latency can be found with SOL - Lat_REM."

The last sentence should be: 

"The AASM definition of the REM latency can be found with **_Lat_REM - SOL._**"

**Comment by raphaelvallat** [comment]
Thank you! Typo fixed in https://github.com/raphaelvallat/yasa/pull/176
