### ISSUE TITLE
Wrong import of Scipy´s Simpson method

### ISSUE THREAD

**Issue by seemingly-ai** [raphaelvallat/yasa#174]
It seems like the naming of that method has changed from "simps" to "simpson". In the file spectral.py the import is still using the old name. 

In spectral.py: from scipy.integrate import simps
New way: from scipy.integrate import simpson as simps
or change all occurrences to simpson

**Comment by raphaelvallat** [comment]
See https://github.com/raphaelvallat/yasa/pull/171
