### ISSUE TITLE
Remove "Avoid too high threshold caused by Artefacts / Motion during Wake"?

### ISSUE THREAD

**Issue by Hockey86** [raphaelvallat/yasa#27]
https://github.com/raphaelvallat/yasa/blob/4b5973bfcf92788f080e3ca05bc2aa1402df8865/yasa/main.py#L660
It uses absolute voltage 10 which does not apply to other scenarios.
Suggest it to be removed, since you already can specify `hypno` and `include` in yasa.spindles_detect.

**Comment by raphaelvallat** [comment]
Hi @Hockey86,

Thanks for opening the issue. So just to clarify, it is in units of standard deviation, and not in unit of absolute voltage:

https://github.com/raphaelvallat/yasa/blob/4b5973bfcf92788f080e3ca05bc2aa1402df8865/yasa/main.py#L653-L658

Now I think you're right that the `min(thresh_rms, 10)` is somewhat arbitrary, and we might as well remove it and just keep the original thresh_rms.

Raphael
