### ISSUE TITLE
automatic_sleep_staging: No module named 'lightbgm'

### ISSUE THREAD

**Issue by 18alia** [raphaelvallat/yasa#28]
When I tried running the 5th code block in the notebook 14_automatic_sleep_staging, I got the error: ModuleNotFoundError: No module named 'lightgbm'
Here is my traceback:
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-66604d5037ad> in <module>
      1 # Getting the predicted sleep stages is now as easy as:
----> 2 y_pred = sls.predict()
      3 y_pred

~\PyMOL\lib\site-packages\yasa\staging.py in predict(self, path_to_model)
    425             self.fit()
    426         # Load and validate pre-trained classifier
--> 427         clf = self._load_model(path_to_model)
    428         # Now we make sure that the features are aligned
    429         X = self._features.copy()[clf.feature_name_]

~\PyMOL\lib\site-packages\yasa\staging.py in _load_model(self, path_to_model)
    398         assert os.path.isfile(path_to_model), "File does not exist."
    399         # Load using Joblib
--> 400         clf = joblib.load(path_to_model)
    401         # Validate features
    402         self._validate_predict(clf)

~\PyMOL\lib\site-packages\joblib\numpy_pickle.py in load(filename, mmap_mode)
    583                     return load_compatibility(fobj)
    584 
--> 585                 obj = _unpickle(fobj, filename, mmap_mode)
    586     return obj

~\PyMOL\lib\site-packages\joblib\numpy_pickle.py in _unpickle(fobj, filename, mmap_mode)
    502     obj = None
    503     try:
--> 504         obj = unpickler.load()
    505         if unpickler.compat_mode:
    506             warnings.warn("The file '%s' has been generated with a "

~\PyMOL\lib\pickle.py in load(self)
   1086                     raise EOFError
   1087                 assert isinstance(key, bytes_types)
-> 1088                 dispatch[key[0]](self)
   1089         except _Stop as stopinst:
   1090             return stopinst.value

~\PyMOL\lib\pickle.py in load_stack_global(self)
   1383         if type(name) is not str or type(module) is not str:
   1384             raise UnpicklingError("STACK_GLOBAL requires str")
-> 1385         self.append(self.find_class(module, name))
   1386     dispatch[STACK_GLOBAL[0]] = load_stack_global
   1387 

~\PyMOL\lib\pickle.py in find_class(self, module, name)
   1424             elif module in _compat_pickle.IMPORT_MAPPING:
   1425                 module = _compat_pickle.IMPORT_MAPPING[module]
-> 1426         __import__(module, level=0)
   1427         if self.proto >= 4:
   1428             return _getattribute(sys.modules[module], name)[0]

ModuleNotFoundError: No module named 'lightgbm'

How do I fix this error? Do I need to install something else? I already tried upgrading yasa with the command`pip install --upgrade yasa`, and it told me all requirements were already satisfied

**Comment by raphaelvallat** [comment]
Hi @18alia,

You need to install the lightgbm package: https://lightgbm.readthedocs.io/en/latest/Python-Intro.html

Thanks
Raphael

**Comment by 18alia** [comment]
Thank you! What else do I need to install to use YASA. I'm assuming I need the things listed on the requirements.txt file, so what is the best way to install all these if I am not GitCloning the entire project?

**Comment by raphaelvallat** [comment]
Hi @18alia,

You can pip install all of the packages in the requirements.txt file, with the exception of the [entropy](https://raphaelvallat.com/entropy/build/html/index.html) package that requires a manual install (via git clone / zip download).

Best,
Raphael
