### ISSUE TITLE
Difficulties implementing the package SleepStaging 

### ISSUE THREAD

**Issue by simon37robledo** [raphaelvallat/yasa#31]
Hi. I am trying to implement YASA to analyse EEG data obtained from birds. I was trying to use the SleepStaging package, but when applying the ".predict" method I am getting the error "File does not exist".
This is an image of the complete error warning. Could you help me with this? I haven't been able to solve the issue, and I checked that all required packages are properly installed. 

![image](https://user-images.githubusercontent.com/38083976/111683297-9468dd80-8825-11eb-9faa-e7af8967f889.png)

king regards from Groningen, the Netherlands.

**Comment by raphaelvallat** [comment]
Hi @simon37robledo,

First of all, please note that the sleep staging module was developed in human sleep data, so it's not gonna work on animal data (rodents, birds, etc). But if you want to try it anyway, then you should make sure that all the files in the yasa/classifiers/ folder (https://github.com/raphaelvallat/yasa/tree/master/yasa/classifiers) are present in your local folder of yasa (e.g. _.../EEG_analysis/lib/python3.9/site-packages/yasa/yasa/classifiers_). If not, you can just download and add them to the folder.

Hope this helps!

Thanks,
Raphael

**Comment by simon37robledo** [comment]
Hi Raphael,

Thanks for the help. I was aware that the staging module was intended for
humans but I wanted to try it anyway. I will try what you recommend. By the
way, do you know of an open source sleep staging package that could be
implemented to non-human data?

Kind regards,

Simon

**Comment by raphaelvallat** [comment]
Hi @simon37robledo,

Got it! Let me know if that works. I am not aware of any open source packages for automatic scoring of animal data. I'm guessing there might be some for rodents sleep, but I doubt there are for birds data.

Closing the issue now, but please feel free to re-open!

Thanks,
Raphael
