### ISSUE TITLE
Error on import: No module named 'entropy'

### ISSUE THREAD

**Issue by joramvanrheede** [raphaelvallat/yasa#32]
Thank you for providing such a useful set of tools to the community! I was keen to try out YASA, andI have just installed YASA via the pip installer as documented in README.md. Unfortunately, on 'import yasa'  I get the following error:

>  File "[...]\yasa\staging.py", line 8, in <module>
>     import entropy as ent
> 
> ModuleNotFoundError: No module named 'entropy'

I see you have recent commits changing 'entropy' to 'antropy' so I guess that that code update may only be partially implemented in the pip install?

**Comment by raphaelvallat** [comment]
Hi @joramvanrheede!

Thanks for opening the issue. You need to install the _entropy_ package manually (with git clone) by following [these instructions](https://raphaelvallat.com/entropy/build/html/index.html). There is unfortunately another package named entropy on the PyPi repository, meaning that it cannot be installed with `pip install entropy`. I have therefore decided last week to duplicate and rename _entropy_ to _antropy_, which can be installed using `pip install antropy`. 

I need to release a new version of YASA that will take into account this change, I'm hoping to do this either this week or the next. But in the meantime, installing EntroPy manually should do the trick 👍 

Thanks,
Raphael

**Comment by joramvanrheede** [comment]
Hi Raphael,
Thank you for the quick response - that solved the problem!
Joram

**Comment by raphaelvallat** [comment]
@joramvanrheede I just released a new version of YASA that solves the problem. Closing the issue, thanks again!
