### ISSUE TITLE
ImportError when running yasa.art_detect and fix

### ISSUE THREAD

**Issue by shengzizeng** [raphaelvallat/yasa#33]
Hi Raphael,

Thanks for developing such an amazing algorithm to analyze sleep data on Python, making life much easier!

However, I encountered import error when using the `yasa.art_detect` regarding the module `sklearn.cluster._kmeans` and want to report this bug and its fix here in case anyone encountered it as well. (not sure if I am doing the right thing in the right place coz I am new to the community, so please forgive me if I am doing it wrong). 

> ImportError: no module named 'sklearn.cluster._kmeans'

This error should be related to the version issue of `scikit-learn`. So you need install the latest version 0.24.1 which contains the function of `sklearn.cluster._kmeans` but I still got the import error:

> File "/opt/anaconda3/lib/python3.7/site-packages/pyriemann/clustering.py", line 5, in <module>
    from sklearn.cluster._kmeans import _init_centroids

> ImportError: cannot import name '_init_centroids' from 'sklearn.cluster._kmeans' (/opt/anaconda3/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py)

This issue is actually because `scikit-learn` 0.24 breaks `pyriemann` , see [Issue](https://github.com/alexandrebarachant/pyRiemann/issues/92) and [fix](https://github.com/alexandrebarachant/pyRiemann/pull/93/files). I think they haven't update the fix on `pyriemann` so one need to manually adjust the code according to this [fix](https://github.com/alexandrebarachant/pyRiemann/pull/93/files).

Now the function `yasa.art_detect` can run properly!

OS version: 10.14.6
Python: 3.7.4

**Comment by shengzizeng** [comment]
In addition, I think it would be nice if the output of `yasa.art_detect` could also contain **annotation information** (including **onset**, **duration** [=5, if using window of 5], and **description** [start with "bad_", so that later epoching can use it for exclusion]). This annotation info which can be easily applied to mne annotation through `mne.Annotations` and will allow for visual inspection of the auto-marked artifacts on the time-domain data. 

Although this could be done within a few costumed code lines, I guess it would be nice if this can be done along with the detection function.

**Comment by raphaelvallat** [comment]
Hi @shengzizeng,

Thanks for opening the issue. It is very unfortunate that pyRiemann isn't maintained anymore. I've actually been considering removing the pyRiemann-based covariance method for artefact rejection because of this exact issue. I hope they release a new version soon, but it doesn't seem like it's gonna happen.

I agree for MNE Annotations. More generally, one could think of a "events_to_annot" function that would allow converting any kind of event detection (artifact, spindles, etc) to MNE-compatible annotations (see also https://github.com/raphaelvallat/yasa/issues/20). I won't have the time to work on this in the near future, but please feel free to open a PR if you'd like!

Thanks

**Comment by ErikBjare** [comment]
@raphaelvallat Good news, Alexandre finally merged my PR yesterday! https://github.com/alexandrebarachant/pyRiemann/pull/93

Thanks for the work on YASA btw, it's been a very helpful reference for my MSc thesis: https://github.com/ErikBjare/thesis

**Comment by raphaelvallat** [comment]
Thanks @ErikBjare for letting me know, and glad to hear that YASA was useful to your thesis (thanks for citing it btw)! I'm just waiting for Alexandre to release a new version of pyRiemann (hopefully soon) and then I'll update YASA!

**Comment by raphaelvallat** [comment]
Fixed in [release 0.5.0](https://github.com/raphaelvallat/yasa/releases/tag/v0.5.0).
