### ISSUE TITLE
Error during automatic sleep staging

### ISSUE THREAD

**Issue by cyberfag** [raphaelvallat/yasa#36]
Hi. I was trying to get the automatically extracted sleep stages, but, while executing sls.predict() command, Python (Jupyter Lab) returned the following error. 
![image](https://user-images.githubusercontent.com/43494532/126310605-48c40535-d306-4531-b043-77c86484748f.png)
I used an edf file loaded `via mne.io.read_raw_edf function(...preload=True...)`: 4 channels (2 EEG, 2 EMG) with the same sf (200 Hz), then I executed `sls = yasa.SleepStaging(raw, eeg_name="EEG1", emg_name="EMG1")` which worked without errors for ~5 seconds, though the file is 26 hours long. I use the newest version of yasa (0.4.1), lightGBM (3.2.1) and antropy (0.1.4) are also installed. Seems like it cannot find the files containing pretrained classifiers. What could it be due to? Because manually I could find the files int the file system.
![image](https://user-images.githubusercontent.com/43494532/126312128-6bc2d514-222b-4819-b5be-2bd3b2cd6ca4.png)
Thanks in advance.

**Comment by cyberfag** [comment]
I added a print() in the staging.py and figured out that path is correct but the classifiers files names are not. As can be seen from the OP post second screenshot, files names also contain a version before the extention, whereas print() indicated that clf_name is just, for example, "clf_eeg+emg", so it doesn't contain package version and cannot be found.

**Comment by raphaelvallat** [comment]
Hi @cyberfag,

Good catch -- I'll make sure to add a classifier for `eeg+emg` in the next release to avoid such errors in the future. 

Thanks!
Raphael

**Comment by raphaelvallat** [comment]
Fixed in [release 0.5.0](https://github.com/raphaelvallat/yasa/releases/tag/v0.5.0).
