### ISSUE TITLE
Automatic Sleep Staging Error

### ISSUE THREAD

**Issue by oo-zz** [raphaelvallat/yasa#37]
Hello,

About 5-6 days ago I started getting the error below when running the following line of code:

y_pred = yasa.SleepStaging(raw, eeg_name="EEG L").predict()
y_pred

I have been using this application for months, nothing has changed on my side. 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-873ffb45b1ff> in <module>
----> 1 y_pred = yasa.SleepStaging(raw, eeg_name="EEG L").predict()
      2 y_pred

~\anaconda3\lib\site-packages\yasa\staging.py in predict(self, path_to_model)
    425             self.fit()
    426         # Load and validate pre-trained classifier
--> 427         clf = self._load_model(path_to_model)
    428         # Now we make sure that the features are aligned
    429         X = self._features.copy()[clf.feature_name_]

~\anaconda3\lib\site-packages\yasa\staging.py in _load_model(self, path_to_model)
    400         clf = joblib.load(path_to_model)
    401         # Validate features
--> 402         self._validate_predict(clf)
    403         return clf
    404 

~\anaconda3\lib\site-packages\yasa\staging.py in _validate_predict(self, clf)
    372         f_diff = np.setdiff1d(clf.feature_name_, self.feature_name_)
    373         if len(f_diff):
--> 374             raise ValueError("The following features are present in the "
    375                              "classifier but not in the current features set:",
    376                              f_diff)

ValueError: ('The following features are present in the classifier but not in the current features set:', array(['eeg_abspow_c5min_norm', 'eeg_abspow_p5min_norm',
       'eeg_alpha_c5min_norm', 'eeg_alpha_p5min_norm',
       'eeg_at_c5min_norm', 'eeg_at_p5min_norm', 'eeg_beta_c5min_norm',
       'eeg_beta_p5min_norm', 'eeg_db_c5min_norm', 'eeg_db_p5min_norm',
       'eeg_ds_c5min_norm', 'eeg_ds_p5min_norm', 'eeg_dt_c5min_norm',
       'eeg_dt_p5min_norm', 'eeg_fdelta_c5min_norm',
       'eeg_fdelta_p5min_norm', 'eeg_hcomp_c5min_norm',
       'eeg_hcomp_p5min_norm', 'eeg_higuchi_c5min_norm',
       'eeg_higuchi_p5min_norm', 'eeg_hmob_c5min_norm',
       'eeg_hmob_p5min_norm', 'eeg_iqr_c5min_norm', 'eeg_iqr_p5min_norm',
       'eeg_kurt_c5min_norm', 'eeg_kurt_p5min_norm', 'eeg_nzc_c5min_norm',
       'eeg_nzc_p5min_norm', 'eeg_perm_c5min_norm', 'eeg_perm_p5min_norm',
       'eeg_petrosian_c5min_norm', 'eeg_petrosian_p5min_norm',
       'eeg_sdelta_c5min_norm', 'eeg_sdelta_p5min_norm',
       'eeg_sigma_c5min_norm', 'eeg_sigma_p5min_norm',
       'eeg_skew_c5min_norm', 'eeg_skew_p5min_norm', 'eeg_std_c5min_norm',
       'eeg_std_p5min_norm', 'eeg_theta_c5min_norm',
       'eeg_theta_p5min_norm'], dtype='<U24'))

**Comment by raphaelvallat** [comment]
Hi @oo-zz,

My mistake — I have released a new version of YASA a few days ago but I forgot to include the latest version of the classifiers. This has now been fixed in the new version of YASA (0.5.1). Make sure to upgrade with: `pip install yasa==0.5.1`

Thanks,
Raphael
