### ISSUE TITLE
Feature request: plot_hypnogram function

### ISSUE THREAD

**Issue by raphaelvallat** [raphaelvallat/yasa#38]
Similar to [yasa.plot_spectrogram](https://raphaelvallat.com/yasa/build/html/generated/yasa.plot_spectrogram.html#yasa.plot_spectrogram) but only the top part:

![image](https://user-images.githubusercontent.com/25703792/129834564-dc53e539-ff03-4016-a11a-42f5b9c9df60.png)

**Comment by skjerns** [comment]
I think this is implemented with version 0.6? :)
