### ISSUE TITLE
Feature request: Bandpower function to output specified ratios (e.g., theta/beta etc)

### ISSUE THREAD

**Issue by apavlo89** [raphaelvallat/yasa#39]
Would be nice to be able to do this easily in YASA :)

**Comment by raphaelvallat** [comment]
Hi @apavlo89,

Thanks for opening the issue! How would you specify the ratios? It's pretty straightforward to calculate from the output of the yasa.bandpower function already (e.g. `data['delta_beta'] = data['delta'] / data['beta']`), and therefore, I'm not sure it is worth burdening the API of the bandpower function.

Thanks,
Raphael
