### ISSUE TITLE
Where are the top 20 most important features of the classifier?

### ISSUE THREAD

**Issue by chenxuesongTHU** [raphaelvallat/yasa#43]
It's a very nice job and useful for academic research and industrial application. I wonder what features play a pivot role in the stage classificaiton, and the paper said the top 20 most important features are illustrated in Figure S2, but I can't find Figure S2 in this URL(https://www.biorxiv.org/content/10.1101/2021.05.28.446165v1.full.pdf). Could you give me some instructions?
Thanks a lot!!!

**Comment by raphaelvallat** [comment]
Hi @chenxuesongTHU,

You can find the figure importance here: https://elifesciences.org/articles/70092/figures#fig1s7. The importance was calculated using this script: https://github.com/raphaelvallat/yasa_classifier/blob/master/05_SHAP_importance.py

Thanks,
Raphael

**Comment by chenxuesongTHU** [comment]
I got it. Thanks again for your contributions to Sleep Research! The nice coding style makes readers enjoy it.
