### ISSUE TITLE
Determining the onset of the REM phase using only EMG data?

### ISSUE THREAD

**Issue by zenbooster** [raphaelvallat/yasa#45]
Hi. Can I determine the onset of the REM phase using only EMG data?

**Comment by raphaelvallat** [comment]
Hi @zenbooster,

I don't think this is really feasible unfortunately. The EMG can be quite similar (= no motion) between deep slow-waves and REM sleep, so I doubt you could ever get a high accuracy detection of REM sleep just from the EMG. I think that the EOG would work better for this task.

Thanks,
Raphael
