### ISSUE TITLE
Detecting sleep spindles

### ISSUE THREAD

**Issue by apoorva6262** [raphaelvallat/yasa#46]
Hi,

I preprocessed the sleep data which was in .edf format in MNE. I changed the channel names in accordance to 1020 montage on MNE and saved it as .set file. I am currently interested in detecting sleep spindles in the n2, n3 and rem phase for c3 and c4 channel. I used the function spindles _detect and got this error (image below). Is it because the data is not getting converted to the right units ? 

![Screenshot 2021-11-04 at 12 47 48](https://user-images.githubusercontent.com/76274425/140409668-187b9eb9-ebf3-4887-9071-9f3036f2184d.png)

Thanks,
Apoorva.

**Comment by raphaelvallat** [comment]
Hi @apoorva6262,

Most likely this is because the data is in Volts (which is the default in MNE), when it should be in microVolts. You can solve this by doing:

```python
sig *= 1e6  # Multiply signal in-place by a million
```

Hope this helps,
Raphael

**Comment by raphaelvallat** [comment]
Hi @apoorva6262,

1) To see average spindles parameters, aggregated by channel and sleep stage (if you specify an hypnogram)
```
sp = yasa.spindles_detect(...)
sp.summary(grp_chan=True, grp_stage=True)
```

2) You should **NOT** filter your data in the sigma band prior to running the spindles detection. Indeed, YASA needs the full broadband signal (e.g. 0.5-30 Hz) to calculate the relative sigma power:

https://github.com/raphaelvallat/yasa/blob/1f83229b6b8315885a51ddb08bbd60e54d40b61c/yasa/detection.py#L615-L627

Thanks,
Raphael
