### ISSUE TITLE
Machine learning model

### ISSUE THREAD

**Issue by Lee-xdu** [raphaelvallat/yasa#48]
hello, Raphael Vallat, what a crazy job. where is the Machine learning model used by yasa-sleep stage scoring. is it a convolutional deep neural network or another? I couldn't find the Model architecture. What shall I do?  please

**Comment by raphaelvallat** [comment]
Hi @Lee-xdu,

The ML model is a LightGBM classifier, as described in the peer-reviewed publication: https://elifesciences.org/articles/70092

The pre-trained classifier can be found at: https://github.com/raphaelvallat/yasa/tree/master/yasa/classifiers

**Comment by Lee-xdu** [comment]
Hi. dear Doctor  Raphael Vallat ,I truly appreciate your timely help！
















At 2021-11-18 01:59:34, "Raphael Vallat" ***@***.***> wrote:

Hi @Lee-xdu,

The ML model is a LightGBM classifier, as described in the peer-reviewed publication: https://elifesciences.org/articles/70092

The pre-trained classifier can be found at: https://github.com/raphaelvallat/yasa/tree/master/yasa/classifiers

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
