### ISSUE TITLE
Understanding `win_sec` in `bandpower`

### ISSUE THREAD

**Issue by matiasandina** [raphaelvallat/yasa#57]
For a second, I was expecting `win_sec` to operate as a rolling window, but after running:

```
yasa.bandpower(eeg_mean100, 
               sf=100,
               ch_names=None, 
               hypno=None, 
               include=None, 
               win_sec=4, 
               relative=False, 
               bandpass=False, 
               #bands=[1, 4, 'Delta', 5, 11, 'Theta'],
               kwargs_welch={'average': 'median', 'window': 'hamming'})
```

I get a `df` that has only one row. Same applies to other arbitrary subsets of the data. The only thing that seems to give more than one power (aka row) is having more channels or stages of a hypnogram. I was hoping to be able to calculate bandpower for arbitrary time windows so I kind of did it with this for loop, but not sure results will make sense, since I don't fully understand what `win_sec` is doing. 

```
import timeit
start_time = timeit.default_timer()
temp_list = []
sliding_window_secs = 4
# signal downsampled to 100Hz
window = sliding_window_secs * 100
windows_to_calculate = eeg_mean100.shape[0]//window
for i in range(windows_to_calculate):
  eeg_sub = eeg_mean100[window*i:window * (i+1)]
  yasa_bands = yasa.bandpower(eeg_sub, 
                  sf=100,
                  ch_names=None, 
                  hypno=None, 
                  include=None, 
                  win_sec=4, 
                  relative=False, 
                  bandpass=False, 
                  bands=[(1, 4, 'Delta'), (5, 11, 'Theta')],
                  kwargs_welch={'average': 'median', 'window': 'hamming'}) 
  temp_list.append(yasa_bands)

yasa_df = pd.concat(temp_list)
print(timeit.default_timer() - start_time)
```
### Update

Upon inspection of the docs/code, I see the actual function of `win_sec` and understand it has nothing to do with what I wanted it to do, so I adjusted my win_sec accordingly. Still my question holds about what would be the recommended way of getting bandpower values every nth data samples.

**Comment by raphaelvallat** [comment]
Hi @matiasandina,

Your method should work well. Perhaps a more optimized method (though less intuitive) is to use:

1. [yasa.sliding_window](https://raphaelvallat.com/yasa/build/html/generated/yasa.sliding_window.html) to convert your data into a 2D (or 3D) array of epochs (e.g. 4-sec epochs of data).
2. Then manually calculate the power spectrum on all epochs at once using [scipy.signal.welch](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.welch.html).
3. Finally, use [yasa.bandpower_from_psd_ndarray](https://raphaelvallat.com/yasa/build/html/generated/yasa.bandpower_from_psd_ndarray.html) to calculate the bandpower on all epochs at once. Note that the output will be a numpy array and not a pandas dataframe.

Alternatively, you could create a vector `mask` of the same length of the data where [ 1 1 1 1 ... 2 2 2 2 .... 3 3 3 3 ... ] 1 = first epoch, 2 = second epoch, etc. Then you can do: `yasa.bandpower(data, sf, hypno=mask, include=(1, 2, 3))` which should calculate the bandpower for each value in `mask` separately.

Hope this helps,
Raphael

**Comment by matiasandina** [comment]
Perfect!
