### ISSUE TITLE
Roadmap to also include other spindle methods?

### ISSUE THREAD

**Issue by skjerns** [raphaelvallat/yasa#69]
Hey Raphael,

once again great work with this toolbox.

Do you plan to also include other spindle algorithms in the future? This would be great for e.g. comparisons with older papers using other methods .

Sometimes reviewers or analysts request a specific method. Most of them are already implement in [wonambi](https://wonambi-python.github.io/gui/methods.html), however, your interface is far superior and much easier to use (wonambi is quite undocumented yet when not using the GUI). E.g. some of the methods that are compared in the [methods paper] (https://doi.org/10.1016/j.jneumeth.2018.08.014) would be great to implement?

Are you already planning to do so in the future?

**Comment by raphaelvallat** [comment]
Hi @skjerns,

Good question. I was not planning on implementing other spindles detection methods. I fear that too many choices is a bad thing, and I actually prefer a single, validated method that performs reasonably well in most cases. That said, I do think that it would be great to include some tools to easily compare detection methods. For example, a yasa.compare_detection function that would tell you the confusion matrix between two detection methods (see [sleepecg.compare_heartbeats](https://sleepecg.readthedocs.io/en/stable/generated/sleepecg.compare_heartbeats.html#sleepecg.compare_heartbeats) for inspiration). 

Or, we could allow users to pass their custom thresholding functions inside yasa.spindles_detect, which would take precedence over the current thresholding methods. For example, you could design a wavelet-based function that would run within the overall framework of YASA and give you the same output format. But this will take a huge amount of work to implement I think.

_PS: I have been wanting to validate the current spindles detection method on the MODA sleep spindle dataset: https://osf.io/8bma7/_

Let me know what you think,

Thanks,
Raphael

**Comment by umair-hassan** [comment]
I also like the idea of creating a comparison matrix property in the class. 

Do you have any idea of what validation matrices you are would like to obtain from the MODA dataset @raphaelvallat . I can definitely help there.

Best,
Umair

**Comment by raphaelvallat** [comment]
Thanks @umair-hassan! My only concern with the MODA dataset is that to download the PSG files you need to submit a formal request approved by the local ethics board. I don't really have the time or energy to do this 😅 . Do you know if there's any other way to access the data? 

> Access to these PSG files requires that the investigators submit a copy of their project (as approved by their local ethics board) and a proof of ethical approval. Upon reception of these documents, the MASS team will provide to the requesting investigators with the whole set of PSG files required for the MODA Gold Standard.

As for validation, I would just like to perform a comparison of YASA's current spindles algorithm against the MODA human consensus scoring. We may want to change the current detection thresholds based on optimization of the F1-score.

Thanks,
Raphael

**Comment by umair-hassan** [comment]
@raphaelvallat  Thank you for your response! I am attempting to obtain the data. Some people I know have used it in the past. I am attempting to contact them, and will update as soon as possible.
