### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by hoechenberger** [raphaelvallat/yasa#74]
Hello @raphaelvallat,

this is basically a copy of https://github.com/raphaelvallat/antropy/issues/18 :) but for `yasa`

I've taken the liberty to add you as a co-maintainer to the `yasa` conda-forge feedstock. Please let me know if that's okay with you! (I just assumed it was)

Again, it might be worthwhile to amend the installation instructions:

https://github.com/conda-forge/yasa-feedstock#installing-yasa

btw we're planning to include `yasa` in the next MNE-Python stand-alone installers:
https://github.com/mne-tools/mne-installers/pull/137

Best wishes,
Richard

**Comment by raphaelvallat** [comment]
Oh wow, this is such a great honor!! Why do you need to include YASA?

**Comment by hoechenberger** [comment]
> Oh wow, this is such a great honor!! Why do you need to include YASA?

The idea behind the MNE installers is that ideally they ship a comprehensive Python environment that allows most users to get their work done without having to manually install additional packages. We're, in fact, including a fairly large number of packages! See: https://github.com/mne-tools/mne-installers/blob/1b9e801144d91527b401b7b138a8cbc0fd5fcd90/recipes/mne-python_1.1/construct.yaml#L67-L130


As for `yasa`, I didn't know this package until a few months or so ago, when a user mentioned it on the MNE forum. I have since then recommended it a few times to forum users and colleagues for certain analyses / visualizations. It's super nicely done and well-documented!

Here are the forum topics where the `yasa` was mentioned:
https://mne.discourse.group/search?q=yasa%20order%3Alatest_topic
