### ISSUE TITLE
ImportError: Numba needs NumPy 1.22 or less

### ISSUE THREAD

**Issue by honeysleep** [raphaelvallat/yasa#91]
!pip list
mne                          1.1.0
numba                        0.56.0
numpy                        1.22.0

when 
```
import yasa

yasa.plot_hypnogram(hypno)
```

**Comment by raphaelvallat** [comment]
I have python 3.8, numba 0.56.0 and numpy 1.22.0 and everything is working well. Are you sure that your numpy version is 1.22 and not 1.23? It seems like numba is only compatible with numpy up to 1.22: https://numba.readthedocs.io/en/stable/user/installing.html

Thanks
Raphael

**Comment by honeysleep** [comment]
I rebooted and it worked out!
