### ISSUE TITLE
direct links to example datasets

### ISSUE THREAD

**Issue by remrama** [raphaelvallat/yasa#96]
I remember being a bit confused about where to find the example data when I started some tutorials a while back. I think it could be a lot easier for people to access if there were direct links within each tutorial. Right now there is one line within a paragraph on the README/homepage that directs people to the notebooks folder:
> The notebooks and datasets can be found on [GitHub](https://github.com/raphaelvallat/yasa/tree/master/notebooks) (make sure that you download the whole notebooks/ folder).

Obviously this is accurate and gets the job done. But it requires a little digging and also seems to assume people are interested in running all the tutorials. I think the more common use is people skimming docs and jumping into the one or two tutorials that serve their needs. So I think adding direct-download links within the tutorials would be wise and make the whole package more accessible, especially for newer trainees or experienced researchers switching to Python.

**Comment by raphaelvallat** [comment]
I agree, I have been wanting to revamp all the notebooks at some point in the near future, so this is definitely something we can add at that point. That said, YASA now includes a "Quickstart" doc section which should be the first tutorial for most users: https://raphaelvallat.com/yasa/build/html/quickstart.html
